version: '2'

services:
  rest:
    build: ./rest
    container_name: rest
    image: appdynamics/sample-app-rest
    environment:
      - CONTROLLER_URL=
      - CONTROLLER_PORT=
      - CONTROLLER_ACCOUNT_NAME=
      - CONTROLLER_ACCESS_KEY=
      - CONTROLLER_USERNAME=
      - CONTROLLER_PASSWORD=
      - PORTAL_USERNAME=
      - PORTAL_PASSWORD=
    links:
      - db
    ports: 
      - "8080:8080"

  db:
    container_name: db
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=singcontroller  
    ports: 
      - "3306:3306"

  web:
    build: ./web
    container_name: web
    image: appdynamics/sample-app-web
    environment:
      - CONTROLLER_URL=
      - CONTROLLER_PORT=
      - CONTROLLER_ACCOUNT_NAME=
      - CONTROLLER_ACCESS_KEY=
    links:
      - rest
      - db
    ports:
      - "3000:3000"
